name: Build and Push Docker Images

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Read current version
      id: read_version
      run: |
        VERSION=$(cat version.txt)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Increment version
      id: increment_version
      run: |
        VERSION=${{ env.VERSION }}
        MAJOR=$(echo "$VERSION" | cut -d '.' -f 1)
        MINOR=$(echo "$VERSION" | cut -d '.' -f 2)
        PATCH=$(echo "$VERSION" | cut -d '.' -f 3)
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        echo "$NEW_VERSION" > version.txt
        echo "IMAGE_TAG=$NEW_VERSION" >> $GITHUB_ENV

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Tag Client Docker Image
      run: |
        docker build -t youssefemzj/mern_projet_ocw_client:${{ env.IMAGE_TAG }} ./client
        docker tag youssefemzj/mern_projet_ocw_client:${{ env.IMAGE_TAG }} youssefemzj/mern_projet_ocw_client:latest

    - name: Build and Tag Server Docker Image
      run: |
        docker build -t youssefemzj/mern_projet_ocw_server:${{ env.IMAGE_TAG }} ./server
        docker tag youssefemzj/mern_projet_ocw_server:${{ env.IMAGE_TAG }} youssefemzj/mern_projet_ocw_server:latest

    - name: Push Client Docker Image to DockerHub
      run: |
        docker push youssefemzj/mern_projet_ocw_client:${{ env.IMAGE_TAG }}
        docker push youssefemzj/mern_projet_ocw_client:latest

    - name: Push Server Docker Image to DockerHub
      run: |
        docker push youssefemzj/mern_projet_ocw_server:${{ env.IMAGE_TAG }}
        docker push youssefemzj/mern_projet_ocw_server:latest

    - name: Create a new branch for changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout -b update-docker-compose-${{ env.IMAGE_TAG }}

    - name: Commit new version to repository
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git add version.txt
        git commit -m "Incremented to version ${{ env.IMAGE_TAG }}"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/YoussefEMZJ/mern_projet_ocw.git HEAD:update-docker-compose-${{ env.IMAGE_TAG }}

    - name: Update docker-compose.yml
      run: |
        sed -i "s|image: youssefemzj/mern_projet_ocw_client:.*|image: youssefemzj/mern_projet_ocw_client:${{ env.IMAGE_TAG }}|g" docker-compose.yml
        sed -i "s|image: youssefemzj/mern_projet_ocw_server:.*|image: youssefemzj/mern_projet_ocw_server:${{ env.IMAGE_TAG }}|g" docker-compose.yml

    - name: Commit updated docker-compose.yml to repository
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git add docker-compose.yml
        git commit -m "Updated docker-compose.yml with version ${{ env.IMAGE_TAG }}"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/YoussefEMZJ/mern_projet_ocw.git HEAD:update-docker-compose-${{ env.IMAGE_TAG }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GH_PAT }}
        commit-message: "Update docker-compose.yml with version ${{ env.IMAGE_TAG }}"
        branch: update-docker-compose-${{ env.IMAGE_TAG }}
        base: develop
        title: "Update docker-compose.yml with version ${{ env.IMAGE_TAG }}"
        body: "This PR updates the docker-compose.yml file with the new image versions."
