name: Deploy on Pre-Prod Server

on:
  push:
    branches:
      - develop
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}  # Utilise le PAT pour bypass la protection

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Read current version
      run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

    - name: Update docker-compose.yml with latest image version
      run: |
        sed -i 's/\(image: youssefemzj\/mern_projet_ocw_client:\).*/\1${{ env.VERSION }}/' docker-compose.yml
        sed -i 's/\(image: youssefemzj\/mern_projet_ocw_server:\).*/\1${{ env.VERSION }}/' docker-compose.yml

    - name: Copy docker-compose.yml to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: 'docker-compose.yml'
        target: '/home/devopsuser/mern_projet_ocw/'
        port: ${{ secrets.VPS_PORT }}  # Utilisation du secret pour le port

    - name: Run Docker Compose on VPS
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}  # Utilisation du secret pour le port
        script: |
          cd /home/devopsuser/mern_projet_ocw
          sudo docker-compose down
          sudo docker-compose up -d
